-- Run this first to set up the database

CREATE DATABASE IF NOT EXISTS flutter_api 
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE flutter_api;

CREATE TABLE IF NOT EXISTS users (
  id         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name       VARCHAR(100)  NOT NULL,
  email      VARCHAR(150)  NOT NULL UNIQUE,
  password   VARCHAR(255)  NOT NULL,
  token      VARCHAR(64)   DEFAULT NULL,
  created_at TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS posts (
  id         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id    INT UNSIGNED  NOT NULL,
  title      VARCHAR(255)  NOT NULL,
  content    TEXT          NOT NULL,
  slug       VARCHAR(255)  NOT NULL UNIQUE,
  status     TINYINT(1)    NOT NULL DEFAULT 1,  -- 1 = published, 0 = draft
  created_at TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
